{% set name = "omicverse" %}
{% set version = "1.6.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d54d20c0df4ae60bd76ca19e5f1d0e3100fa88020e2de6bdb033f05ed65103bd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit >=3.2,<4
    - python >=3.8
    - pip

  run:
    - python >=3.9
    - numpy >=1.23
    - pandas >=1.5
    - matplotlib-base <3.7
    - scikit-learn >=1.2
    - scipy >=1.8,<1.12
    - pytorch >=1.8
    - networkx >=2.8
    - seaborn >=0.11
    - scvi-tools >=0.20.1
    - scanpy >=1.10
    - scikit-misc >=0.1
    - lifelines >=0.27
    - einops >=0.6
    - tqdm >=4.64
    - hnswlib >=0.7
    - multiprocess >=0.70
    - gdown >=4.6
    - python-igraph >=0.10
    - datashader >=0.14
    - termcolor >=2.1
    - leidenalg >=0.8
    - adjusttext >=0.7
    - boltons >=23.0
    - ipywidgets >=8.0
    - pygam >=0.8.0
    - tensorboard >=2.6
    - mellon >=1.3
    - pytorch_geometric
    - plotly
    - pynvml
    - tqdm
    - bioservices
    - transformers
    - pot
    - wget
    - tomli

test:
  imports:
    - omicverse

about:
  home: https://github.com/Starlitnightly/omicverse
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A python library for multi omics included bulk, single and spatial cell RNA-seq analysis.
  dev_url: https://github.com/Starlitnightly/omicverse

extra:
  recipe-maintainers:
    - Starlitnightly
