{% set name = "omicverse" %}
{% set version = "1.4.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 317d629ab3d260a3420e277ee824d4d917bc04c03d2a5ad1b8432ae5300f55f6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit >=3.2,<4
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - numpy >=1.22,<1.24
    - pandas <=1.5.3
    - matplotlib-base <3.7
    - scikit-learn >=1.2
    - scipy >=1.8
    - pytorch >=1.8
    - networkx >=2.8
    - seaborn >=0.11
    - scvi-tools >=0.20.1
    - scanpy >=1.8
    - scikit-misc >=0.1
    - lifelines >=0.27
    - einops >=0.6
    - tqdm >=4.64
    - hnswlib >=0.7
    - multiprocess >=0.70
    - gdown >=4.6
    - python-igraph >=0.10
    - datashader >=0.14
    - termcolor >=2.1
    - leidenalg >=0.8
    - adjusttext >=0.7
    - boltons >=23.0
    - ipywidgets >=8.0
    - pygam >=0.8.0
    - tensorboard >=2.6

test:
  imports:
    - omicverse

about:
  home: https://github.com/Starlitnightly/omicverse
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A python library for multi omics included bulk and single cell RNA-seq analysis.
  dev_url: https://github.com/Starlitnightly/omicverse

extra:
  recipe-maintainers:
    - Starlitnightly

